user:
  #username 学号或者工号
  username: '161105024'
  #address 地址，定位信息
  address: 中国四川省成都市金牛区一环路北1段-129号-附9号
  #email 接受通知消息的邮箱
  email: 461009747@qq.com
  #school 学校全称
  school: 福州大学
  #lon 经度
  lon: '113.939491'
  #lat 纬度
  lat: '35.294774'
  #abnormalReason 不在范围的原因
  abnormalReason:
  #photo 签到照片，不需要可不填，或者直接删除
  photo: jkm.png
#今日校园相关配置
cpdaily:
  #表单组默认选项配置
  defaults:
    #表单默认选项配置，按顺序，注意，只有标必填项的才处理
    - default:
      #表单项类型，对应今日校园接口返回的fieldType字段，1代表文本，2代表单选，3代表多选，4代表图片